---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: zencar-backend-dev
  namespace: zencar-dev
  annotations:
    fluxcd.io/automated: "false"
    # fluxcd.io/tag.chart-image: glob:3.1.1-debian-9-*
spec:
  releaseName: zencar-backend-dev
  chart:
    git: ssh://git@github.com/quaternion/flux-get-started
    ref: master
    path: charts/zencar-backend
  values:
    imagePullSecrets:
      - name: zen-car-github-packages  
    # image:
    #   repository: bitnami/ghost
    #   tag: 3.1.1-debian-9-r0
    # persistence:
    #   enabled: false
    # resources:
    #   requests:
    #     memory: 32Mi
    #     cpu: 10m
    service:
      type: ClusterIP
    # mariadb:
    #   master:
    #     persistence:
    #       enabled: false
